modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "${github_url}issues/"
showAsResourcePack = false

[[mods]]
modId = "squaremap"
version = "${version}"
displayName = "squaremap"
displayURL = "${github_url}"
authors = "jmp"
description = "${description}"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.squaremap]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.squaremap]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.squaremap]]
modId = "cloud"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "squaremap-forge.mixins.json"
